### ISSUE TITLE
Bug in converting tasks resources

### ISSUE THREAD

**Issue by aleasims** [gevulotnetwork/gevulot-rs#64]
https://github.com/gevulotnetwork/gevulot-rs/blob/v0.3.0/src/models/task.rs#L206-L207

Looks like we are not converting millicores from proto into cores, which are expected in `CoreUnit`.

`proto.cpus` are expected to be in millicores and using `<CoreUnit as From<u64>>::from` will result into `CoreUnit::Number(proto.cpus)`. But it have to be `CoreUnit::Number(proto.cpus / 1000)` instead.

However when running `gvltctl task get` for some old example task from docs, it surprisingly returns correct result:

```
gvltctl task get -e "$GEVULOT_ENDPOINT" e870966891918f11f192ccbc383d65a2a39ce5a3e62a82955cb12a06f7972831
...
resources:
    cpus: 1
    gpus: 0
    memory: 512
    time: 120
```

Unfortunately I can't create new example task now and check it, cause Firestarter fails to handle task creation:

```
$ gvltctl task create -e "$GEVULOT_ENDPOINT" -n "$GEVULOT_MNEMONIC" -f task.yaml
Error: RpcConnectionError("status: NotFound, message: \"tx not found: E9E70ED1A2D2D7945DA01D61A70D3080A7E47D3088C11F73CCF85CBED7ADD35A\", details: [], metadata: MetadataMap { headers: {\"server\": \"nginx/1.27.4\", \"date\": \"Tue, 18 Mar 2025 17:04:58 GMT\", \"content-type\": \"application/grpc\", \"x-cosmos-block-height\": \"6661465\", \"via\": \"1.1 google\", \"content-length\": \"0\", \"alt-svc\": \"h3=\\\":443\\\"; ma=2592000,h3-29=\\\":443\\\"; ma=2592000\"} }")
```

I'm not sure about the units in Worker Spec, but [this](https://github.com/gevulotnetwork/gevulot-rs/blob/v0.3.0/src/models/worker.rs#L140-L141) may be the same bug.
